import "@babel/polyfill";
import 'nodelist-foreach-polyfill';
import elementClosest from 'element-closest';
elementClosest(window);
import 'formdata-polyfill';
import 'fetch-polyfill';
import 'es6-promise';

import toggleTel from './modules/toggleTel';
import toggleMenu from './modules/toggleMenu';
import smoothScroll from './modules/smoothScroll';
import popUpListeners from './modules/popUpListeners';
import formsHandler from './modules/formsHandler';
import hints from './modules/hints';
import sliderRepair from './modules/sliderRepair';
import sliderPortfolio from './modules/sliderPortfolio';
import sliderTransparency from './modules/sliderTransparency';
import tabsDesign from './modules/tabsDesign';
import sliderReviews from './modules/sliderReviews';
import tabsProcess from './modules/tabsProcess';
import accordeon from './modules/accordeon';
import carousel from './modules/carousel';
import getPricesData from './modules/getPricesData';

toggleTel();
toggleMenu();
smoothScroll();
popUpListeners();
formsHandler();
hints();
sliderRepair();
sliderPortfolio();
sliderTransparency();
tabsDesign();
sliderReviews();
tabsProcess();
accordeon();
carousel();
getPricesData();

